### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by hvital** [unlooped/FuzzySearchJS#5]
Does this project MIT (https://spdx.org/licenses/MIT.html) licensed like listed in npm registry (https://www.npmjs.com/package/fuzzysearch-js)?

Could you guys please add a LICENSE file to this repo?

**Comment by n3o77** [comment]
Hi @hvital i just added the license.

**Comment by hvital** [comment]
Awesome. Many thanks!!!!
